<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260330092203 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE annonce (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, statut VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, categorie_id INT NOT NULL, createur_id INT NOT NULL, helper_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F65593E5BCF5E72D ON annonce (categorie_id)');
        $this->addSql('CREATE INDEX IDX_F65593E573A201E5 ON annonce (createur_id)');
        $this->addSql('CREATE INDEX IDX_F65593E5D7693E95 ON annonce (helper_id)');
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE annonce ADD CONSTRAINT FK_F65593E5BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE annonce ADD CONSTRAINT FK_F65593E573A201E5 FOREIGN KEY (createur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE annonce ADD CONSTRAINT FK_F65593E5D7693E95 FOREIGN KEY (helper_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE annonce DROP CONSTRAINT FK_F65593E5BCF5E72D');
        $this->addSql('ALTER TABLE annonce DROP CONSTRAINT FK_F65593E573A201E5');
        $this->addSql('ALTER TABLE annonce DROP CONSTRAINT FK_F65593E5D7693E95');
        $this->addSql('DROP TABLE annonce');
        $this->addSql('DROP TABLE categorie');
    }
}
